name: pindou
description: 个人使用的抖音与小红书媒体解析工具。
publish_to: none

version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  video_player: ^2.14.0
  get_video_thumbnail: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
